apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - anyuid-rolebinding.yaml
  - external-firefly-credentials.yaml
  - external-firefly-db-firefly.yaml
  - external-firefly-db-superuser.yaml
  - firefly-cronjob.yaml
  - firefly.yaml
  - firefly-fints-importer.yaml
  - postgresql-database.yaml
  - privileged-rolebinding.yaml
  - ./backup
